name: OwnWorld
version: 1.0
main: net.costelboyt.ownworld.OwnWorld
api-version: '1.21'
commands:
  ownworld:
    description: Manage your custom 5x5 world territory.
    permission: ownworld.use
    usage: /ownworld <create|join|back> [world_name]

permissions:
  ownworld.use:
    description: Allows players to use the ownworld commands.
    default: true